//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="PoliciesInfo", Namespace="http://schemas.datacontract.org/2004/07/")]
public partial class PoliciesInfo : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string AccountNumberField;
    
    private string BankField;
    
    private string DepositAmountField;
    
    private System.DateTime DocumentDateField;
    
    private string DocumentNumberField;
    
    private string EconomicField;
    
    private string InvoiceField;
    
    private string PaymentFolioField;
    
    private string PolicyField;
    
    private string ReferenceIdField;
    
    private string SerialField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AccountNumber
    {
        get
        {
            return this.AccountNumberField;
        }
        set
        {
            this.AccountNumberField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Bank
    {
        get
        {
            return this.BankField;
        }
        set
        {
            this.BankField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DepositAmount
    {
        get
        {
            return this.DepositAmountField;
        }
        set
        {
            this.DepositAmountField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DocumentDate
    {
        get
        {
            return this.DocumentDateField;
        }
        set
        {
            this.DocumentDateField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DocumentNumber
    {
        get
        {
            return this.DocumentNumberField;
        }
        set
        {
            this.DocumentNumberField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Economic
    {
        get
        {
            return this.EconomicField;
        }
        set
        {
            this.EconomicField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Invoice
    {
        get
        {
            return this.InvoiceField;
        }
        set
        {
            this.InvoiceField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string PaymentFolio
    {
        get
        {
            return this.PaymentFolioField;
        }
        set
        {
            this.PaymentFolioField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Policy
    {
        get
        {
            return this.PolicyField;
        }
        set
        {
            this.PolicyField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ReferenceId
    {
        get
        {
            return this.ReferenceIdField;
        }
        set
        {
            this.ReferenceIdField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Serial
    {
        get
        {
            return this.SerialField;
        }
        set
        {
            this.SerialField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISAPService")]
public interface ISAPService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPService/GetPoliciesInfo", ReplyAction="http://tempuri.org/ISAPService/GetPoliciesInfoResponse")]
    PoliciesInfo GetPoliciesInfo(string policy, string invoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAPService/GetPoliciesInfo", ReplyAction="http://tempuri.org/ISAPService/GetPoliciesInfoResponse")]
    System.Threading.Tasks.Task<PoliciesInfo> GetPoliciesInfoAsync(string policy, string invoice);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISAPServiceChannel : ISAPService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SAPServiceClient : System.ServiceModel.ClientBase<ISAPService>, ISAPService
{
    
    public SAPServiceClient()
    {
    }
    
    public SAPServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SAPServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public PoliciesInfo GetPoliciesInfo(string policy, string invoice)
    {
        return base.Channel.GetPoliciesInfo(policy, invoice);
    }
    
    public System.Threading.Tasks.Task<PoliciesInfo> GetPoliciesInfoAsync(string policy, string invoice)
    {
        return base.Channel.GetPoliciesInfoAsync(policy, invoice);
    }
}
