// <auto-generated />
using System;
using BCWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PIServiceAPI.Migrations
{
    [DbContext(typeof(PolicyInformationDbContext))]
    [Migration("20220810165533_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PIServiceAPI.Models.PolicyInformationService", b =>
                {
                    b.Property<int>("PolicyInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyInfoId"), 1L, 1);

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("EmitterCenter")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("InfoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentFolio")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("PolicyInfoId");

                    b.ToTable("PoliciesInformationService");
                });
#pragma warning restore 612, 618
        }
    }
}
